import dynamic from 'next/dynamic';
import Head from 'next/head';

const Carousel = dynamic(() => import('@/components/carousel/carousel'), {
  ssr: false,
});

const images = [
  'https://picsum.photos/1000/300',
  'https://picsum.photos/1000/300',
  'https://picsum.photos/1000/300',
  'https://picsum.photos/1000/300',
];

export default function Home() {
  return (
    <>
      <Head>
        <title>Amae Store</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Carousel images={images} />
    </>
  );
}
